spring:
  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    schema: schema.sql

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    mongodb:
      host: localhost
      port: 27017
      database: books-db

mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.spring.barsegyan.config.mongock
