spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:data.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true


logging:
  level:
    root: info
  file:
    path: ./application_logs

management:
  endpoints:
    web:
      exposure:
        include: "metrics,health,logfile"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true