spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
    schema: classpath:/schema.sql
    data: classpath:/data.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true

discount-service:
  url: http://localhost:8081