version: "3"
services:
  frontend:
    depends_on:
      - backend
    build:
      context: ./book-application-frontend
      args:
        - API_URL=http://backend:8080
    ports:
      - "3000:80"

  backend:
    depends_on:
      - postgres
    build:
      context: ./book-application-backend
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres

  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
