spring:
  data:
    mongodb:
      database: books-db

mongock:
#  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.barsegyan.mongock.changelog

